### ISSUE TITLE
Could not find com.github.puskal-khadka:MultiSelectSpinner:1.0.0.

### ISSUE THREAD

**Issue by petered** [puskal-khadka/MultiSelectSpinner#2]
When I add the dependency:

```
dependencies {
    ...
    implementation 'com.github.puskal-khadka:MultiSelectSpinner:1.0.0'
}
```

 and try to build, I get:

```
org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.github.puskal-khadka:MultiSelectSpinner:1.0.0.
```

**Comment by puskal-khadka** [comment]
Use the latest version  i.e.   1.0.1

implementation 'com.github.puskal-khadka:MultiSelectSpinner:1.0.1'

**Comment by maszlaizsani** [comment]
I have the same issue.. 

org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.github.puskal-khadka:MultiSelectSpinner:1.0.1.
