### ISSUE TITLE
Selected value issue

### ISSUE THREAD

**Issue by rmbhati** [puskal-khadka/MultiSelectSpinner#3]
If i need to select some value default.
then how can i do?

for example: 
i am view data then how can i show selected data?

**Comment by Hmerman6006** [comment]
Try setting a `TextView` below the `MultipleSpinnerView` and use the `selectedSectionListener` arrow function argument of the `buildCheckedSpinner` function:
```
binding.multipleSelectSpinnerView.buildCheckedSpinner(stringList) { selectedPositionList, displayString ->
        binding.tvMultipleSpinnerChoice.text = displayString
}
```
For more complex data I suggest you change the `String` list to your expected data class or for something more re-useable create a `SpinnerItem` data class:
```
data class SpinnerItem(val id: Long, val display: String, val item: Any?)
```
Then build your `ArrayList<SpinnerItem>`  list and amend the `MultipleSelectSpinner` argument list to accept the list of `SpinnerItem` objects.  It is very easy just replace all `String` arguments with `SpinnerItem`. 
The changes to the `MultipleSelectSpinnerPojo` data class will lead you:
```
data class MultipleSelectSpinnerPojo(
    var item: SpinnerItem,
    var isSelected:Boolean
)
```
Then it becomes:
```
binding.multipleSelectSpinnerView.buildCheckedSpinner(spinnerItems) { selectedPositionList, displayString ->
    val q = arrayListOf<YourCustomDataObject>()
    selectedPositionList.filter { it.item != null }.forEach { q.add(it.item as YourCustomDataObject) }  // Cast to your object
    if(q.isNotEmpty()) {
        binding.tvMultipleSpinnerChoice.text = displayString
        //  viewModel.setYourCustomDataObject(q)  //  If you have a view model, set it
    } else {
        binding.tvMultipleSpinnerChoice.text = ""
    }
}
```

**Comment by puskal-khadka** [comment]
regarding how to show data using this multiSelectSpinner library, @Hmerman6006  answered well in the above comment. For now, selecting the default option is not allowed, but it will be a nice feature to implement and will be added to this library in the near future.
